-- =====================================================
-- SUPPLY CHAIN DATA WAREHOUSE - DM LAYER
-- Script 2: Default Rows (Run ONCE)
-- =====================================================
SET search_path = BL_DM, public;
-- =====================================================
-- SECTION : DEFAULT ROWS INSERTION
-- =====================================================

-- Default row for Customers
INSERT INTO BL_DM.DIM_CUSTOMERS (CUSTOMER_SURR_ID, CUSTOMER_SRC_ID, CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME,
                          CUSTOMER_FULL_NAME, CUSTOMER_GENDER, CUSTOMER_YEAR_OF_BIRTH, CUSTOMER_EMAIL,
                          CUSTOMER_SEGMENT, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, -1, 'n.a.', 'n.a.', 'n.a.', 'n.a.', 1900, 'n.a.', 'n.a.', 'MANUAL', 'CE_CUSTOMERS'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_CUSTOMERS WHERE CUSTOMER_SURR_ID = -1);

-- Default row for Geographies
INSERT INTO BL_DM.DIM_GEOGRAPHIES (GEOGRAPHY_SURR_ID, GEOGRAPHY_SRC_ID, CITY_NAME, CITY_SRC_ID, STATE_NAME, STATE_SRC_ID,
                            STATE_CODE, COUNTRY_NAME, COUNTRY_SRC_ID, COUNTRY_CODE, REGION_NAME, REGION_SRC_ID,
                            SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, -1, 'n.a.', -1, 'n.a.', -1, 'n.a.', 'n.a.', -1, 'n.a.', 'n.a.', -1, 'MANUAL', 'CE_GEOGRAPHIES'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_GEOGRAPHIES WHERE GEOGRAPHY_SURR_ID = -1);

-- Default row for Sales Representatives
INSERT INTO BL_DM.DIM_SALES_REPRESENTATIVES (SALES_REP_SURR_ID, SALES_REP_SRC_ID, SALES_REP_NAME, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, -1, 'n.a.', 'MANUAL', 'CE_SALES_REPRESENTATIVES'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_SALES_REPRESENTATIVES WHERE SALES_REP_SURR_ID = -1);

-- Default row for Warehouses
INSERT INTO BL_DM.DIM_WAREHOUSES (WAREHOUSE_SURR_ID, WAREHOUSE_SRC_ID, WAREHOUSE_NAME, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, -1, 'n.a.', 'MANUAL', 'CE_WAREHOUSES'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_WAREHOUSES WHERE WAREHOUSE_SURR_ID = -1);

-- Default row for Carriers
INSERT INTO BL_DM.DIM_CARRIERS (CARRIER_SURR_ID, CARRIER_SRC_ID, CARRIER_NAME, CARRIER_TYPE, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, -1, 'n.a.', 'n.a.', 'MANUAL', 'CE_CARRIERS'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_CARRIERS WHERE CARRIER_SURR_ID = -1);

-- Default row for Order Statuses
INSERT INTO BL_DM.DIM_ORDER_STATUSES (ORDER_STATUS_SURR_ID, ORDER_STATUS_SRC_ID, ORDER_STATUS, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, -1, 'n.a.', 'MANUAL', 'CE_ORDER_STATUSES'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_ORDER_STATUSES WHERE ORDER_STATUS_SURR_ID = -1);

-- Default row for Payment Methods
INSERT INTO BL_DM.DIM_PAYMENT_METHODS (PAYMENT_METHOD_SURR_ID, PAYMENT_METHOD_SRC_ID, PAYMENT_METHOD, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, -1, 'n.a.', 'MANUAL', 'CE_PAYMENT_METHODS'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_PAYMENT_METHODS WHERE PAYMENT_METHOD_SURR_ID = -1);

-- Default row for Shipping Modes
INSERT INTO BL_DM.DIM_SHIPPING_MODES (SHIPPING_MODE_SURR_ID, SHIPPING_MODE_SRC_ID, SHIPPING_MODE, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, -1, 'n.a.', 'MANUAL', 'CE_SHIPPING_MODES'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_SHIPPING_MODES WHERE SHIPPING_MODE_SURR_ID = -1);

-- Default row for Delivery Statuses
INSERT INTO BL_DM.DIM_DELIVERY_STATUSES (DELIVERY_STATUS_SURR_ID, DELIVERY_STATUS_SRC_ID, DELIVERY_STATUS, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, -1, 'n.a.', 'MANUAL', 'CE_DELIVERY_STATUSES'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_DELIVERY_STATUSES WHERE DELIVERY_STATUS_SURR_ID = -1);

-- Default row for Products (SCD Type 2)
INSERT INTO BL_DM.DIM_PRODUCTS_SCD (PRODUCT_SURR_ID, START_DT, PRODUCT_SRC_ID, PRODUCT_NAME, BRAND_NAME, BRAND_SRC_ID,
                             PRIMARY_CATEGORY_SRC_ID, PRIMARY_CATEGORY_NAME, DEPARTMENT_SRC_ID, DEPARTMENT_NAME,
                             ALL_CATEGORY_SRC_IDS, ALL_CATEGORY_NAMES, PRODUCT_STATUS_NAME, PRODUCT_STATUS_SRC_ID,
                             END_DT, IS_ACTIVE, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, '1990-01-01', -1, 'n.a.', 'n.a.', -1, -1, 'n.a.', -1, 'n.a.', -1, 'n.a.', 'n.a.', -1,
       '9999-12-31', 'Y', 'MANUAL', 'CE_PRODUCTS_SCD'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_PRODUCTS_SCD WHERE PRODUCT_SURR_ID = -1);

-- Default row for Time Dimension (for missing dates)
INSERT INTO BL_DM.DIM_TIME_DAY (DT_SURR_ID, CALENDAR_DT, YEAR_NUM, QUARTER_NUM, MONTH_NUM, WEEK_NUM, DAY_NUM,
                         DAY_OF_YEAR_NUM, DAY_OF_WEEK_NUM, MONTH_NAME, MONTH_NAME_SHORT, DAY_NAME, DAY_NAME_SHORT,
                         QUARTER_NAME, YEAR_QUARTER, YEAR_MONTH, IS_WEEKEND, IS_HOLIDAY, HOLIDAY_NAME,
                         SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT 19000101, '1900-01-01', 1900, 1, 1, 1, 1, 1, 1,
       'Unknown',     -- MONTH_NAME (fits in VARCHAR(20))
       'UNK',         -- MONTH_NAME_SHORT (fits in VARCHAR(3))
       'Unknown',     -- DAY_NAME (fits in VARCHAR(20))
       'UNK',         -- DAY_NAME_SHORT (fits in VARCHAR(3))
       'Q1',          -- QUARTER_NAME (fits in VARCHAR(10))
       '1900-Q1',     -- YEAR_QUARTER (fits in VARCHAR(10))
       '1900-01',     -- YEAR_MONTH (fits in VARCHAR(10))
       FALSE, FALSE, 'Unknown', 'MANUAL', 'DIM_TIME_DAY'
WHERE NOT EXISTS (SELECT 1 FROM BL_DM.DIM_TIME_DAY WHERE DT_SURR_ID =19000101 );


-- =====================================================
-- SECTION : VERIFICATION QUERIES
-- =====================================================

-- Verify default rows
SELECT 'DIM_CUSTOMERS' as table_name, COUNT(*) as default_rows
FROM BL_DM.DIM_CUSTOMERS
WHERE CUSTOMER_SURR_ID = -1
UNION ALL
SELECT 'DIM_GEOGRAPHIES', COUNT(*)
FROM BL_DM.DIM_GEOGRAPHIES
WHERE GEOGRAPHY_SURR_ID = -1
UNION ALL
SELECT 'DIM_SALES_REPRESENTATIVES', COUNT(*)
FROM BL_DM.DIM_SALES_REPRESENTATIVES
WHERE SALES_REP_SURR_ID = -1
UNION ALL
SELECT 'DIM_WAREHOUSES', COUNT(*)
FROM BL_DM.DIM_WAREHOUSES
WHERE WAREHOUSE_SURR_ID = -1
UNION ALL
SELECT 'DIM_CARRIERS', COUNT(*)
FROM BL_DM.DIM_CARRIERS
WHERE CARRIER_SURR_ID = -1
UNION ALL
SELECT 'DIM_ORDER_STATUSES', COUNT(*)
FROM BL_DM.DIM_ORDER_STATUSES
WHERE ORDER_STATUS_SURR_ID = -1
UNION ALL
SELECT 'DIM_PAYMENT_METHODS', COUNT(*)
FROM BL_DM.DIM_PAYMENT_METHODS
WHERE PAYMENT_METHOD_SURR_ID = -1
UNION ALL
SELECT 'DIM_SHIPPING_MODES', COUNT(*)
FROM BL_DM.DIM_SHIPPING_MODES
WHERE SHIPPING_MODE_SURR_ID = -1
UNION ALL
SELECT 'DIM_DELIVERY_STATUSES', COUNT(*)
FROM BL_DM.DIM_DELIVERY_STATUSES
WHERE DELIVERY_STATUS_SURR_ID = -1
UNION ALL
SELECT 'DIM_PRODUCTS_SCD', COUNT(*)
FROM BL_DM.DIM_PRODUCTS_SCD
WHERE PRODUCT_SURR_ID = -1
UNION ALL
SELECT 'DIM_TIME_DAY', COUNT(*)
FROM BL_DM.DIM_TIME_DAY
WHERE DT_SURR_ID = 19000101;
